import sys

try:
    sys.exit('123123')
except Exception:
    print('exception')